# Generated by Django 2.2.7 on 2019-11-14 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_news_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='slug',
        ),
    ]
